LOAD DATA
INFILE 'pedidos.txt'
INTO TABLE pedidos
FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  id         INTEGER EXTERNAL,
  cliente_id INTEGER EXTERNAL,
  fecha      DATE "YYYY-MM-DD",
  total      INTEGER EXTERNAL
)
